version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: skyops-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fleetManagerDB
    ports:
      - "5432:5432"
    volumes:
      - skyops-db-data:/var/lib/postgresql/data
      - ./dump-fleetManagerDB-30-07-26.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - skyops-network
  
  redis:
    image: redis:7-alpine
    container_name: skyops-redis
    ports:
      - "6379:6379"
    networks:
      - skyops-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: skyops-backend
    restart: always
    profiles: ["apps"]
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=skyops-postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=fleetManagerDB
      - CACHE_HOST=skyops-redis
      - CACHE_PORT=6379
    networks:
      - skyops-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skyops-frontend
    restart: always
    profiles: ["apps"]
    ports:
      - "5173:80"
    networks:
      - skyops-network

volumes:
  skyops-db-data:

networks:
  skyops-network:
    driver: bridge
