import { MS_PER_DAY } from './time.constant';

export const MAINTENANCE_INTERVAL_DAYS = 90;
export const MAINTENANCE_INTERVAL_FLIGHT_HOURS = 50;
export const MAINTENANCE_INTERVAL_MS = MAINTENANCE_INTERVAL_DAYS * MS_PER_DAY;
export const MAINTENANCE_FLIGHT_HOURS_TOLERANCE = 2;

